name: Supabase Schema Snapshot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create docs folder
        run: mkdir -p docs/db

      - name: Dump schema with pg_dump 17 (Docker)
        env:
          SUPABASE_DB_URL_SESSION: ${{ secrets.SUPABASE_DB_URL_SESSION }}
        run: |
          docker run --rm \
            -e SUPABASE_DB_URL_SESSION="$SUPABASE_DB_URL_SESSION" \
            -v "$PWD:/work" -w /work \
            postgres:17-alpine \
            sh -lc 'pg_dump "$SUPABASE_DB_URL_SESSION" --schema-only --no-owner --no-privileges -f docs/db/schema.sql'

      - name: Commit schema snapshot if changed
        run: |
          if [[ -n "$(git status --porcelain docs/db)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/db
            git commit -m "chore(db): update schema snapshot"
            git push
          else
            echo "No schema changes."
          fi
