name: Supabase Schema Snapshot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Ensure pg_dump is available
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Create docs folder
        run: mkdir -p docs/db

      # Schema-only dump (includes tables, indexes, policies, functions — no data)
      - name: Dump schema with pg_dump 17 (Docker)
        env:
          SUPABASE_DB_URL_SESSION: ${{ secrets.SUPABASE_DB_URL_SESSION }}
        run: |
          docker run --rm \
          -e PGPASSWORD="$(echo "$SUPABASE_DB_URL_SESSION" | sed -n 's/.*:\([^:@]*\)@.*/\1/p')" \
          -v "$PWD:/work" -w /work \
          postgres:17-alpine \
          sh -lc 'pg_dump "$SUPABASE_DB_URL_SESSION" --schema-only --no-owner --no-privileges --file docs/db/schema.sql'


      # (Optional) Public-only dump too
      # - name: Dump public schema only
      #   env:
      #     SUPABASE_DB_URL_SESSION: ${{ secrets.SUPABASE_DB_URL_SESSION }}
      #   run: |
      #     pg_dump "$SUPABASE_DB_URL_SESSION" \
      #       --schema=public \
      #       --schema-only \
      #       --no-owner \
      #       --no-privileges \
      #       --file docs/db/schema_public.sql

      - name: Commit schema snapshot if changed
        run: |
          if [[ -n "$(git status --porcelain docs/db)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/db
            git commit -m "chore(db): update schema snapshot"
            git push
          else
            echo "No schema changes."
          fi
